server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - GlobalFilter
        - LoggingFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG